project:
  type: book

book:
  title: "Open Source Software Development: A socio-technical course"
  author: "James Howison (and contributing TAs)"
  page-navigation: true
  chapters:
    - index.qmd
    - syllabus.Rmd
    # - paper_planes_innovation.qmd
    # - paper_planes_version_control.qmd
    - part: "Insights"
    # - part: insights.qmd
      chapters: 
         - insights/what_is_open_source.qmd
    #     - motivations.qmd
         - insights/licenses.qmd
    #     - coordination.qmd
    #     - governance.qmd
    #     - knowledge_sharing.qmd
    #     - documentation.qmd
    #     - bias_and_lack_of_diversity.qmd
    #     - agile_development.qmd
    #     - stack_and_stream.qmd
    #     - cybersecurity_oss.qmd
    # 
    # - part: skills.qmd
    #   chapters:
    #     - git_basic_workflow.qmd
    #     - git_rewinding_work.qmd
    #     - git_branching.qmd
    #     - git_sharing_conflicts.qmd
    #     - git_collaboration.qmd
    #     - unit_tests.qmd
    #     - continuous_integration.qmd
    #     - git_release_management.qmd
    #     - python_packaging.qmd
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

