project:
  type: book
  output-dir: ../docs

book:
  title: "Open Source Software Development: A socio-technical course"
  author: "James Howison (and contributing TAs)"
  page-navigation: true
  sidebar:
    style: "docked"
  chapters:
    - index.qmd
    - oss_syllabus.Rmd
    - part: "Insights"
      chapters:
      - insights/what_is_open_source.qmd
      - insights/motivations.qmd
      - insights/licenses.qmd
      - insights/coordination.qmd
    #     - governance.qmd
    #     - knowledge_sharing.qmd
    #     - documentation.qmd
    #     - bias_and_lack_of_diversity.qmd
    #     - agile_development.qmd
    #     - stack_and_stream.qmd
    #     - cybersecurity_oss.qmd
    
    
    - part: "Skills"
      chapters:
      - skills/git_basic_workflow.qmd
      - skills/git_rewinding_work.qmd
      - skills/branching.qmd
      - skills/github_solo.qmd
      - skills/github_collaboration.Rmd
    #     - git_sharing_conflicts.qmd
    #     - git_collaboration.qmd
    #     - unit_tests.qmd
    #     - continuous_integration.qmd
    #     - git_release_management.qmd
    #     - python_packaging.qmd
    
  appendices:
    - skills/skills_faq.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
#    highlight-style: espresso

editor: visual

